### ISSUE TITLE
Sea-Foods: Kanban Setup

### ISSUE THREAD

**Issue by Lameck1** [Lameck1/Sea-Foods#21]
# Description
Link to project: [Sea-Foods](https://github.com/Lameck1/Sea-Foods/projects/1)

The contributors to this project are two, namely:
- [Lameck Otieno](https://github.com/Lameck1)
- [Olawale](https://github.com/olawale-o)

**Comment by dasileker** [comment]
Hi @Lameck1

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- You have done a great job, but the link provided is not the one supposed to be, it should be a link to your **`Projects`** 👉[look at this please](https://user-images.githubusercontent.com/61562626/127870396-213802c0-991a-477a-b631-faa57f5a8aa6.jpeg)




_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lameck1** [comment]
Thanks, @dasileker for pointing that out. Necessary change applied.

**Comment by Dipeshtwis** [comment]
# Hi @Lameck1 and @olawale-o , 

### Status: Approved ✔️

:+1:  Great work on making the suggested changes. Well Done.


Your project is complete!  There are some optional changes that is highly recommended I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Highly Recommended:
- [ ] Decide who is `Student A`, `Student B`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students) and All cards with group task in the title should be assigned to someone (it does not matter to whom as you have freedom with that).
- [ ] The issue should use a circle with user's avatar on each card. See the example below:

<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/22434660/127869037-f6a6909b-7c2e-4da8-a6cb-f2e1ff326702.png">

### Your's issue card look like:

![Screenshot from 2021-08-02 19-24-36](https://user-images.githubusercontent.com/22434660/127873249-6f4728b7-b0ea-4d20-bfd3-b4c17e74c968.png)


**You may close this issue link**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Dipesh Kumar_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by olawale-o** [comment]
Hi @Dipeshtwis 
Thank you for your time and we really appreciate the optional changes you pointed out.
Keep up the good work

**Comment by Lameck1** [comment]
Thanks, @Dipeshtwis. Suggestions appreciated.
